FROM ubuntu:16.04

LABEL company="HEWLETT PACKARD ENTERPRISE" \
      maintainer="SIVAKALYAN SULLURU" \
      Location="Banglore" \
      Version="11.0"

# httpd is the package name for apache in Linux
# apache2 is the package name for apache in Ubuntu
RUN apt-get update -y 
RUN apt-get install apache2 -y
RUN apt-get install wget -y
RUN apt-get unzip -yml


# Copy the static website to Apache deployment directory(/var/www/html) WORKDIR /var/www/html

WORKDIR /tmp

RUN wget https://github.com/Dev-siva/Teams/archive/master.zip
RUN unzip master.zip

RUN cp -r Teams-master/* /var/www/html/


EXPOSE 80
# CMD is runtime instruction, is excuted when we run container
ENTRYPOINT ["apachectl","-D", "FOREGROUND"]

